ALTER TABLE jobs
ADD COLUMN IF NOT EXISTS countries TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TABLE jobs
ADD COLUMN IF NOT EXISTS salary_text TEXT;

ALTER TABLE jobs
ADD COLUMN IF NOT EXISTS experience_text TEXT;

ALTER TABLE jobs
ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE jobs
ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_jobs_active
ON jobs (active);
